// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdwMAfVsyAJyrMs5n4vAXzv_6Pv79FBtE',
    appId: '1:175636124949:web:81fa749a2a6750a49dc51c',
    messagingSenderId: '175636124949',
    projectId: 'giydir-mvp2',
    authDomain: 'giydir-mvp2.firebaseapp.com',
    storageBucket: 'giydir-mvp2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbSQbaVQMsIRXKLgtnr9q0mJeZqw1-FDU',
    appId: '1:175636124949:android:0ebaf1d53b9ca1259dc51c',
    messagingSenderId: '175636124949',
    projectId: 'giydir-mvp2',
    storageBucket: 'giydir-mvp2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlF8WTuwVEeGGhbvFFifSDQWN87ZFSAPk',
    appId: '1:175636124949:ios:5fa7fd0c3441bb9b9dc51c',
    messagingSenderId: '175636124949',
    projectId: 'giydir-mvp2',
    storageBucket: 'giydir-mvp2.appspot.com',
    iosBundleId: 'com.example.giydirMvp2',
  );
}
